### ISSUE TITLE
Download toolkit according to the given version.

### ISSUE THREAD

**Issue by huichen-cs** [huichen-cs/GhIssuesFromSarifAction#1]
As in the following, we want to download the toolkit matching the version given. 
```
    - id: sarif-to-issues
      name: SARIF-to-GitHub-Issues-Action-All-In-One
      uses: huichen-cs/GhIssuesFromSarifAction/sariftoghissues@v0.004.alpha
      with:
        toolkit-version: v0.001'
        sarif-data-path: '${{github.workspace}}/sarif_results'
        qhelp-root: 'http://www.sci.brooklyn.cuny.edu/~chen/uploads/research/qhelp'
        issue-data-path: '_s2ghi_/issue_data'
        repository: '${{github.repository}}'
        sha: '${{github.sha}}'
      env:
        GH_TOKEN: '${{secrets.GITHUB_TOKEN}}'
```
